basePath: /api
definitions:
  ap_manager.ActiveAp:
    properties:
      connection_id:
        type: string
      device_id:
        type: string
    type: object
  api.CommonResponse:
    properties:
      data: {}
      error:
        type: string
      status:
        type: integer
    type: object
  api.ModemShortInfo:
    properties:
      id:
        type: string
    type: object
  nm_connection_manager.NmCommonSettings:
    properties:
      autoconnect:
        type: string
      id:
        type: string
      permissions:
        items:
          type: string
        type: array
      timestamp:
        type: integer
      type:
        type: string
      uuid:
        type: string
    type: object
  nm_connection_manager.NmConnection:
    properties:
      common_settings:
        $ref: '#/definitions/nm_connection_manager.NmCommonSettings'
      id:
        type: string
      wireless_security_settings:
        $ref: '#/definitions/nm_connection_manager.NmWirelessSecuritySettings'
      wireless_settings:
        $ref: '#/definitions/nm_connection_manager.NmWirelessSettings'
    type: object
  nm_connection_manager.NmWirelessSecuritySettings:
    properties:
      key-mgmt:
        type: string
    type: object
  nm_connection_manager.NmWirelessSettings:
    properties:
      mac-address:
        type: string
      mac-address-blacklist:
        items:
          type: string
        type: array
      mode:
        type: string
      security:
        type: string
      seen-bssids:
        items:
          type: string
        type: array
      ssid:
        description: SSID              []uint8  `mapstructure:"ssid"`
        type: string
    type: object
  nm_device_manager.DeviceDetailedInfo:
    properties:
      auto_connect:
        type: boolean
      driver:
        type: string
      driver_version:
        type: string
      firmware_missing:
        type: boolean
      fw_version:
        type: string
      id:
        type: string
      interface:
        type: string
      managed:
        type: boolean
      mtu:
        type: integer
      nm_plugin_missing:
        type: boolean
      physical_port_id:
        type: string
      real:
        type: boolean
      state:
        type: string
      type:
        type: string
    type: object
  nm_device_manager.DeviceShortInfo:
    properties:
      driver:
        type: string
      id:
        type: string
      interface:
        type: string
      state:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
  description: API for network management - AP, ethernet, modems.
  title: OrAP Service API
  version: "0.1"
paths:
  /ap/active:
    get:
      consumes:
      - application/json
      description: Get list of active AP with info about Connection-Device
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with list of active AP
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/ap_manager.ActiveAp'
                  type: array
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: List of active AP
      tags:
      - ap_info
  /ap/compatible_devices:
    get:
      consumes:
      - application/json
      description: 'Get list of devices with short info: id, name, description and
        connection state.'
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with list of devices
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/nm_device_manager.DeviceShortInfo'
                  type: array
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: List of network devices for AP
      tags:
      - ap_info
  /ap/connections:
    get:
      consumes:
      - application/json
      description: 'Get list of AP connection settings with short info: id, name,
        description and connection state.'
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with list of AP connections
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/nm_connection_manager.NmConnection'
                  type: array
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: List of AP connections
      tags:
      - ap_info
  /auth/token:
    post:
      consumes:
      - application/json
      description: Get JWT token for sent username and password.
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with JWT as data
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: User Login method
      tags:
      - auth
  /devices:
    get:
      consumes:
      - application/json
      description: 'Get list of devices with short info: id, name, description and
        connection state.'
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with list of devices
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/nm_device_manager.DeviceShortInfo'
                  type: array
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: List of network devices
      tags:
      - devices_info
  /devices/{device_id}:
    get:
      consumes:
      - application/json
      description: 'Get info about device: common info, state, etc.'
      parameters:
      - description: Device id from list of devices
        in: path
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with modem detailed info as data
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/nm_device_manager.DeviceDetailedInfo'
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "404":
          description: Device not found error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: Device detailed information
      tags:
      - devices_info
  /modems:
    get:
      consumes:
      - application/json
      description: 'Get list of modems with short info: id, name, description and
        connection state.'
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with list of modems
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.ModemShortInfo'
                  type: array
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: List of modems
      tags:
      - modems_info
  /modems/{modem_id}:
    get:
      consumes:
      - application/json
      description: 'Get info about modem: common info, state, etc.'
      parameters:
      - description: Modem id from list of modems
        in: path
        name: modem_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Common JSON response with modem detailed info as data
          schema:
            allOf:
            - $ref: '#/definitions/api.CommonResponse'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: Unauthorized error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "404":
          description: Modem not found error
          schema:
            $ref: '#/definitions/api.CommonResponse'
        "500":
          description: Unhandled server error
          schema:
            $ref: '#/definitions/api.CommonResponse'
      security:
      - BasicAuth: []
      summary: Modem detailed information
      tags:
      - modems_info
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
tags:
- description: Auth operations
  name: auth
- description: Common operations
  name: common
- description: AP info operation
  name: ap_info
- description: Devices info operations
  name: devices_info
- description: Modems info operations
  name: modems_info
